version: '2'

services:

  deployment1:
    image: tomcat:9
    ports:
      - "8081:8080"
    container_name: tomcat1

  deployment2:
    image: tomcat:8
    ports:
      - "8082:8080"
    container_name: tomcat2

  web:
    image: nginx
    container_name: Nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/etc/nginx/conf.d
    command: [nginx-debug, '-g', 'daemon off;']
