version: '2'

services:

  deployment1:
    image: srinivasbv22/guns
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=database
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    container_name: tomcat1
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=guns
      - MYSQL_ROOT_PASSWORD=root
    
    ports:
      - "8082:3306"
    volumes:
      - /var/lib/data_storage:/var/lib/mysql
      - /var/mysqldata:/docker-entrypoint-initdb.d
