version: '2'

services:

  deployment1:
    image: gireeshgg/tomguns:latest
    depends_on:
      - database
    ports:
      - "8083:8080"
    container_name: app1

  deployment2:
    image: gireeshgg/tomguns:latest
    depends_on:
      - database
    ports:
      - "8082:8080"
    container_name: app2
    
  database:
    container_name: flask_mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /var/data1:/var/lib/mysql
      - /var/mysqldata/init:/docker-entrypoint-initdb.d
    command: "true"
    ports:
      - "3306:3306"
