apiVersion: v1
kind: Service
metadata:
  name: gunsui
  labels:
    role: gunsroleui
spec:
  selector:
    role: gunsroleui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  type: NodePort
